
CREATE TABLE IF NOT EXISTS users
(   
    id SERIAL PRIMARY KEY NOT NULL,
    uuid UUID DEFAULT gen_random_uuid() NOT NULL,
    username VARCHAR(300) UNIQUE NOT NULL,
    passwordcrypt TEXT NOT NULL,
    usertype VARCHAR(50) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

